name: Build

concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Clean old builds (optional)
        run: rm -f **/*.cs3 || true

      - name: Build Plugin
        run: |
          chmod +x ./gradlew
          ./gradlew make makePluginsJson

      - name: List Output
        run: |
          echo "✅ Build complete. Output files:"
          find . -name "*.cs3"
